import React from 'react'
import type { CustomLinkButton } from './types'
import {
  Link as LinkIcon,
  Globe,
  Sparkles,
  BookOpen,
  Video,
  Download,
  ShoppingBag,
  Calendar,
  Headphones,
  Star,
  MessageCircle,
  Phone,
  Mail,
  MapPin,
  Send,
  Camera,
  Mic,
  Music,
  FileText,
  Code,
  GraduationCap,
  ShoppingCart,
  Store,
  Tag,
  CreditCard,
  Coffee,
  Gift,
  Briefcase,
  DollarSign,
  Truck,
  Flame,
  Heart,
  Rocket,
  Award,
  ShieldCheck,
  Lightbulb,
  Zap,
  Utensils,
  Package,
} from 'lucide-react'

export interface IconPreset {
  id: string
  label: string
  labelAr?: string
  labelEn?: string
  category: 'social' | 'business' | 'media' | 'highlight'
  bgClass: string
  textClass: string
  borderClass: string
  icon: React.ComponentType<{ className?: string }>
}

export interface CategoryItem {
  id: string
  label: string
  labelAr: string
  labelEn: string
}

export const FLATICON_CATEGORIES: readonly CategoryItem[] = [
  { id: 'all', label: 'الكل', labelAr: 'الكل', labelEn: 'All' },
  { id: 'social', label: 'تواصل وشبكات', labelAr: 'تواصل وشبكات', labelEn: 'Social & Chat' },
  { id: 'business', label: 'تجارة وخدمات', labelAr: 'تجارة وخدمات', labelEn: 'Business & Store' },
  { id: 'media', label: 'ميديا ومحتوى', labelAr: 'ميديا ومحتوى', labelEn: 'Media & Content' },
  { id: 'highlight', label: 'تفاعل وتميز', labelAr: 'تفاعل وتميز', labelEn: 'Featured & Badges' },
]

export const FLATICON_PRESETS: IconPreset[] = [
  // Social & Communication
  {
    id: 'whatsapp',
    label: 'واتساب',
    labelAr: 'واتساب',
    labelEn: 'WhatsApp',
    category: 'social',
    bgClass: 'bg-emerald-500/10 dark:bg-emerald-500/20',
    textClass: 'text-emerald-600 dark:text-emerald-400',
    borderClass: 'border-emerald-500/25',
    icon: MessageCircle,
  },
  {
    id: 'telegram',
    label: 'تليغرام',
    labelAr: 'تليغرام',
    labelEn: 'Telegram',
    category: 'social',
    bgClass: 'bg-sky-500/10 dark:bg-sky-500/20',
    textClass: 'text-sky-500 dark:text-sky-400',
    borderClass: 'border-sky-500/25',
    icon: Send,
  },
  {
    id: 'phone',
    label: 'اتصال هاتفي',
    labelAr: 'اتصال هاتفي',
    labelEn: 'Phone Call',
    category: 'social',
    bgClass: 'bg-green-500/10 dark:bg-green-500/20',
    textClass: 'text-green-600 dark:text-green-400',
    borderClass: 'border-green-500/25',
    icon: Phone,
  },
  {
    id: 'email',
    label: 'بريد إلكتروني',
    labelAr: 'بريد إلكتروني',
    labelEn: 'Email',
    category: 'social',
    bgClass: 'bg-rose-500/10 dark:bg-rose-500/20',
    textClass: 'text-rose-500 dark:text-rose-400',
    borderClass: 'border-rose-500/25',
    icon: Mail,
  },
  {
    id: 'globe',
    label: 'موقع ويب',
    labelAr: 'موقع ويب',
    labelEn: 'Website',
    category: 'social',
    bgClass: 'bg-blue-500/10 dark:bg-blue-500/20',
    textClass: 'text-blue-600 dark:text-blue-400',
    borderClass: 'border-blue-500/25',
    icon: Globe,
  },
  {
    id: 'location',
    label: 'خريطة وعنوان',
    labelAr: 'خريطة وعنوان',
    labelEn: 'Map & Address',
    category: 'social',
    bgClass: 'bg-amber-500/10 dark:bg-amber-500/20',
    textClass: 'text-amber-600 dark:text-amber-400',
    borderClass: 'border-amber-500/25',
    icon: MapPin,
  },
  {
    id: 'link',
    label: 'رابط عام',
    labelAr: 'رابط عام',
    labelEn: 'Custom Link',
    category: 'social',
    bgClass: 'bg-purple-500/10 dark:bg-purple-500/20',
    textClass: 'text-purple-600 dark:text-purple-400',
    borderClass: 'border-purple-500/25',
    icon: LinkIcon,
  },

  // Business & Commerce
  {
    id: 'shopping',
    label: 'متجر ومنتجات',
    labelAr: 'متجر ومنتجات',
    labelEn: 'Shop & Items',
    category: 'business',
    bgClass: 'bg-purple-500/10 dark:bg-purple-500/20',
    textClass: 'text-purple-600 dark:text-purple-400',
    borderClass: 'border-purple-500/25',
    icon: ShoppingBag,
  },
  {
    id: 'cart',
    label: 'سلة شراء',
    labelAr: 'سلة شراء',
    labelEn: 'Cart & Checkout',
    category: 'business',
    bgClass: 'bg-indigo-500/10 dark:bg-indigo-500/20',
    textClass: 'text-indigo-600 dark:text-indigo-400',
    borderClass: 'border-indigo-500/25',
    icon: ShoppingCart,
  },
  {
    id: 'store',
    label: 'فرع ومعرض',
    labelAr: 'فرع ومعرض',
    labelEn: 'Branch & Store',
    category: 'business',
    bgClass: 'bg-violet-500/10 dark:bg-violet-500/20',
    textClass: 'text-violet-600 dark:text-violet-400',
    borderClass: 'border-violet-500/25',
    icon: Store,
  },
  {
    id: 'discount',
    label: 'عرض وخصم',
    labelAr: 'عرض وخصم',
    labelEn: 'Offer & Sale',
    category: 'business',
    bgClass: 'bg-red-500/10 dark:bg-red-500/20',
    textClass: 'text-red-500 dark:text-red-400',
    borderClass: 'border-red-500/25',
    icon: Tag,
  },
  {
    id: 'payment',
    label: 'دفع وبطاقة',
    labelAr: 'دفع وبطاقة',
    labelEn: 'Payment & Cards',
    category: 'business',
    bgClass: 'bg-teal-500/10 dark:bg-teal-500/20',
    textClass: 'text-teal-600 dark:text-teal-400',
    borderClass: 'border-teal-500/25',
    icon: CreditCard,
  },
  {
    id: 'price',
    label: 'أسعار وباقات',
    labelAr: 'أسعار وباقات',
    labelEn: 'Prices & Plans',
    category: 'business',
    bgClass: 'bg-emerald-500/10 dark:bg-emerald-500/20',
    textClass: 'text-emerald-600 dark:text-emerald-400',
    borderClass: 'border-emerald-500/25',
    icon: DollarSign,
  },
  {
    id: 'calendar',
    label: 'حجز وموعد',
    labelAr: 'حجز وموعد',
    labelEn: 'Booking & Date',
    category: 'business',
    bgClass: 'bg-blue-500/10 dark:bg-blue-500/20',
    textClass: 'text-blue-600 dark:text-blue-400',
    borderClass: 'border-blue-500/25',
    icon: Calendar,
  },
  {
    id: 'briefcase',
    label: 'أعمال واستشارة',
    labelAr: 'أعمال واستشارة',
    labelEn: 'Business & Consult',
    category: 'business',
    bgClass: 'bg-slate-500/10 dark:bg-slate-500/20',
    textClass: 'text-slate-700 dark:text-slate-300',
    borderClass: 'border-slate-500/25',
    icon: Briefcase,
  },
  {
    id: 'coffee',
    label: 'كافيه وقهوة',
    labelAr: 'كافيه وقهوة',
    labelEn: 'Cafe & Coffee',
    category: 'business',
    bgClass: 'bg-amber-600/10 dark:bg-amber-600/20',
    textClass: 'text-amber-700 dark:text-amber-400',
    borderClass: 'border-amber-600/25',
    icon: Coffee,
  },
  {
    id: 'food',
    label: 'مطعم ووجبات',
    labelAr: 'مطعم ووجبات',
    labelEn: 'Food & Meals',
    category: 'business',
    bgClass: 'bg-orange-500/10 dark:bg-orange-500/20',
    textClass: 'text-orange-600 dark:text-orange-400',
    borderClass: 'border-orange-500/25',
    icon: Utensils,
  },
  {
    id: 'gift',
    label: 'هدية ومفاجأة',
    labelAr: 'هدية ومفاجأة',
    labelEn: 'Gift & Surprise',
    category: 'business',
    bgClass: 'bg-pink-500/10 dark:bg-pink-500/20',
    textClass: 'text-pink-600 dark:text-pink-400',
    borderClass: 'border-pink-500/25',
    icon: Gift,
  },
  {
    id: 'delivery',
    label: 'شحن وتوصيل',
    labelAr: 'شحن وتوصيل',
    labelEn: 'Delivery & Ship',
    category: 'business',
    bgClass: 'bg-cyan-500/10 dark:bg-cyan-500/20',
    textClass: 'text-cyan-600 dark:text-cyan-400',
    borderClass: 'border-cyan-500/25',
    icon: Truck,
  },
  {
    id: 'package',
    label: 'طرد ومنتجات',
    labelAr: 'طرد ومنتجات',
    labelEn: 'Package & Box',
    category: 'business',
    bgClass: 'bg-yellow-600/10 dark:bg-yellow-600/20',
    textClass: 'text-yellow-700 dark:text-yellow-400',
    borderClass: 'border-yellow-600/25',
    icon: Package,
  },

  // Media & Content
  {
    id: 'video',
    label: 'فيديو ويوتيوب',
    labelAr: 'فيديو ويوتيوب',
    labelEn: 'Video & YouTube',
    category: 'media',
    bgClass: 'bg-red-500/10 dark:bg-red-500/20',
    textClass: 'text-red-600 dark:text-red-400',
    borderClass: 'border-red-500/25',
    icon: Video,
  },
  {
    id: 'music',
    label: 'صوتيات وموسيقى',
    labelAr: 'صوتيات وموسيقى',
    labelEn: 'Music & Audio',
    category: 'media',
    bgClass: 'bg-fuchsia-500/10 dark:bg-fuchsia-500/20',
    textClass: 'text-fuchsia-600 dark:text-fuchsia-400',
    borderClass: 'border-fuchsia-500/25',
    icon: Music,
  },
  {
    id: 'podcast',
    label: 'بودكاست ومايك',
    labelAr: 'بودكاست ومايك',
    labelEn: 'Podcast & Mic',
    category: 'media',
    bgClass: 'bg-purple-600/10 dark:bg-purple-600/20',
    textClass: 'text-purple-600 dark:text-purple-400',
    borderClass: 'border-purple-600/25',
    icon: Mic,
  },
  {
    id: 'headphones',
    label: 'سماعات واستماع',
    labelAr: 'سماعات واستماع',
    labelEn: 'Headphones',
    category: 'media',
    bgClass: 'bg-indigo-500/10 dark:bg-indigo-500/20',
    textClass: 'text-indigo-600 dark:text-indigo-400',
    borderClass: 'border-indigo-500/25',
    icon: Headphones,
  },
  {
    id: 'camera',
    label: 'تصوير وفوتو',
    labelAr: 'تصوير وفوتو',
    labelEn: 'Photo & Camera',
    category: 'media',
    bgClass: 'bg-pink-500/10 dark:bg-pink-500/20',
    textClass: 'text-pink-600 dark:text-pink-400',
    borderClass: 'border-pink-500/25',
    icon: Camera,
  },
  {
    id: 'book',
    label: 'كتالوج وكتاب',
    labelAr: 'كتالوج وكتاب',
    labelEn: 'Catalog & Book',
    category: 'media',
    bgClass: 'bg-amber-500/10 dark:bg-amber-500/20',
    textClass: 'text-amber-600 dark:text-amber-400',
    borderClass: 'border-amber-500/25',
    icon: BookOpen,
  },
  {
    id: 'article',
    label: 'مقال وملف PDF',
    labelAr: 'مقال وملف PDF',
    labelEn: 'Article & PDF',
    category: 'media',
    bgClass: 'bg-blue-500/10 dark:bg-blue-500/20',
    textClass: 'text-blue-600 dark:text-blue-400',
    borderClass: 'border-blue-500/25',
    icon: FileText,
  },
  {
    id: 'download',
    label: 'تحميل ملف',
    labelAr: 'تحميل ملف',
    labelEn: 'Download File',
    category: 'media',
    bgClass: 'bg-emerald-500/10 dark:bg-emerald-500/20',
    textClass: 'text-emerald-600 dark:text-emerald-400',
    borderClass: 'border-emerald-500/25',
    icon: Download,
  },
  {
    id: 'code',
    label: 'برمجة وكود',
    labelAr: 'برمجة وكود',
    labelEn: 'Code & Dev',
    category: 'media',
    bgClass: 'bg-slate-700/10 dark:bg-slate-700/30',
    textClass: 'text-slate-800 dark:text-slate-200',
    borderClass: 'border-slate-600/25',
    icon: Code,
  },
  {
    id: 'education',
    label: 'دورة وتعليم',
    labelAr: 'دورة وتعليم',
    labelEn: 'Course & Learn',
    category: 'media',
    bgClass: 'bg-violet-500/10 dark:bg-violet-500/20',
    textClass: 'text-violet-600 dark:text-violet-400',
    borderClass: 'border-violet-500/25',
    icon: GraduationCap,
  },

  // Highlights & Interaction
  {
    id: 'sparkles',
    label: 'سحر ولمعان',
    labelAr: 'سحر ولمعان',
    labelEn: 'Magic & Glow',
    category: 'highlight',
    bgClass: 'bg-amber-400/15 dark:bg-amber-400/25',
    textClass: 'text-amber-500 dark:text-amber-400',
    borderClass: 'border-amber-400/30',
    icon: Sparkles,
  },
  {
    id: 'flame',
    label: 'ترند وشائع',
    labelAr: 'ترند وشائع',
    labelEn: 'Trend & Hot',
    category: 'highlight',
    bgClass: 'bg-orange-500/15 dark:bg-orange-500/25',
    textClass: 'text-orange-500 dark:text-orange-400',
    borderClass: 'border-orange-500/30',
    icon: Flame,
  },
  {
    id: 'star',
    label: 'نجمة ومفضل',
    labelAr: 'نجمة ومفضل',
    labelEn: 'Star & Favorite',
    category: 'highlight',
    bgClass: 'bg-yellow-400/15 dark:bg-yellow-400/25',
    textClass: 'text-yellow-600 dark:text-yellow-400',
    borderClass: 'border-yellow-400/30',
    icon: Star,
  },
  {
    id: 'heart',
    label: 'قلب ومحبة',
    labelAr: 'قلب ومحبة',
    labelEn: 'Heart & Like',
    category: 'highlight',
    bgClass: 'bg-rose-500/15 dark:bg-rose-500/25',
    textClass: 'text-rose-500 dark:text-rose-400',
    borderClass: 'border-rose-500/30',
    icon: Heart,
  },
  {
    id: 'rocket',
    label: 'انطلاق وسريع',
    labelAr: 'انطلاق وسريع',
    labelEn: 'Rocket & Speed',
    category: 'highlight',
    bgClass: 'bg-purple-500/15 dark:bg-purple-500/25',
    textClass: 'text-purple-600 dark:text-purple-400',
    borderClass: 'border-purple-500/30',
    icon: Rocket,
  },
  {
    id: 'award',
    label: 'شهادة وجائزة',
    labelAr: 'شهادة وجائزة',
    labelEn: 'Award & Winner',
    category: 'highlight',
    bgClass: 'bg-amber-500/15 dark:bg-amber-500/25',
    textClass: 'text-amber-600 dark:text-amber-400',
    borderClass: 'border-amber-500/30',
    icon: Award,
  },
  {
    id: 'verified',
    label: 'موثق ورسمي',
    labelAr: 'موثق ورسمي',
    labelEn: 'Verified & Official',
    category: 'highlight',
    bgClass: 'bg-emerald-500/15 dark:bg-emerald-500/25',
    textClass: 'text-emerald-600 dark:text-emerald-400',
    borderClass: 'border-emerald-500/30',
    icon: ShieldCheck,
  },
  {
    id: 'idea',
    label: 'فكرة وإلهام',
    labelAr: 'فكرة وإلهام',
    labelEn: 'Idea & Spark',
    category: 'highlight',
    bgClass: 'bg-yellow-500/15 dark:bg-yellow-500/25',
    textClass: 'text-yellow-600 dark:text-yellow-400',
    borderClass: 'border-yellow-500/30',
    icon: Lightbulb,
  },
  {
    id: 'zap',
    label: 'فوري وطاقة',
    labelAr: 'فوري وطاقة',
    labelEn: 'Instant & Power',
    category: 'highlight',
    bgClass: 'bg-amber-500/15 dark:bg-amber-500/25',
    textClass: 'text-amber-600 dark:text-amber-400',
    borderClass: 'border-amber-500/30',
    icon: Zap,
  },
]

export function getLinkPreset(iconId?: string): IconPreset {
  const found = FLATICON_PRESETS.find((p) => p.id === iconId)
  if (found) return found
  return FLATICON_PRESETS.find((p) => p.id === 'link') || FLATICON_PRESETS[0]
}

export const DEFAULT_SAMPLE_LINKS: CustomLinkButton[] = [
  {
    id: 'sample_whatsapp',
    title: 'محادثة مباشرة عبر واتساب',
    subtitle: 'رد فوري واستفسار سريع على مدار الساعة',
    url: 'https://www.youtube.com/',
    icon: 'whatsapp',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_telegram',
    title: 'قناتنا الرسمية على تليغرام',
    subtitle: 'أحدث الأخبار والتحديثات الحصرية أولاً بأول',
    url: 'https://www.youtube.com/',
    icon: 'telegram',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_phone',
    title: 'اتصال هاتفي وخدمة العملاء',
    subtitle: 'فريق الدعم جاهز للإجابة على جميع اتصالاتكم',
    url: 'https://www.youtube.com/',
    icon: 'phone',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_email',
    title: 'مراسلتنا عبر البريد الإلكتروني',
    subtitle: 'للشراكات والاستفسارات الرسمية المباشرة',
    url: 'https://www.youtube.com/',
    icon: 'email',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_globe',
    title: 'زيارة موقعنا الإلكتروني الرسمي',
    subtitle: 'تصفح خدماتنا ومشاريعنا المتكاملة عبر الويب',
    url: 'https://www.youtube.com/',
    icon: 'globe',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_location',
    title: 'موقعنا الجغرافي على خرائط Google',
    subtitle: 'زيارة المقر الرئيسي وصالات الاستقبال',
    url: 'https://www.youtube.com/',
    icon: 'location',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_link',
    title: 'المدونة والمقالات الحصرية',
    subtitle: 'نصائح وإرشادات متخصصة ومحدثة دورياً',
    url: 'https://www.youtube.com/',
    icon: 'link',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_shopping',
    title: 'متجر المنتجات الرقمية والتصاميم',
    subtitle: 'تصفح واشترِ القوالب والتصاميم الحصرية فوراً',
    url: 'https://www.youtube.com/',
    icon: 'shopping',
    highlight: true,
    is_active: true,
  },
  {
    id: 'sample_cart',
    title: 'سلة المشتريات والطلبات الفورية',
    subtitle: 'أكمل طلبك واستمتع بتوصيل فوري وسريع',
    url: 'https://www.youtube.com/',
    icon: 'cart',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_store',
    title: 'فروعنا وصالات العرض المعتمدة',
    subtitle: 'تفضل بزيارة أقرب معرض لتجربة خدماتنا مباشرة',
    url: 'https://www.youtube.com/',
    icon: 'store',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_discount',
    title: 'كوبونات وعروض وخصومات حصرية',
    subtitle: 'تخفيضات مميزة تصل إلى 50% لفترة محدودة',
    url: 'https://www.youtube.com/',
    icon: 'discount',
    highlight: true,
    is_active: true,
  },
  {
    id: 'sample_payment',
    title: 'طرق الدفع والتحويل البنكي الآمن',
    subtitle: 'خيارات دفع متعددة وموثوقة تناسب الجميع',
    url: 'https://www.youtube.com/',
    icon: 'payment',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_price',
    title: 'جدول الأسعار والباقات التنافسية',
    subtitle: 'اختر الباقة المثالية لاحتياجاتك وميزانيتك',
    url: 'https://www.youtube.com/',
    icon: 'price',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_calendar',
    title: 'حجز موعد أو استشارة خاصة 1-on-1',
    subtitle: 'جلسة توجيه ومراجعة شخصية مع خبير معتمد',
    url: 'https://www.youtube.com/',
    icon: 'calendar',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_briefcase',
    title: 'حلول الأعمال والخدمات المؤسسية',
    subtitle: 'استشارات متقدمة لتطوير الشركات ورواد الأعمال',
    url: 'https://www.youtube.com/',
    icon: 'briefcase',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_coffee',
    title: 'قائمة القهوة المختصة والمشروبات',
    subtitle: 'تذوق أرقى محاصيل القهوة بنكهات استثنائية',
    url: 'https://www.youtube.com/',
    icon: 'coffee',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_food',
    title: 'منيو المطعم والوجبات الخاصة',
    subtitle: 'أطباق طازجة محضرة بأعلى معايير الجودة',
    url: 'https://www.youtube.com/',
    icon: 'food',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_gift',
    title: 'بطاقات الهدايا والمفاجآت الخاصة',
    subtitle: 'أهدِ من تحب تجربة فريدة مع قسائمنا الشرائية',
    url: 'https://www.youtube.com/',
    icon: 'gift',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_delivery',
    title: 'تتبع الشحنات والتوصيل السريع',
    subtitle: 'خدمة توصيل موثوقة وفورية لباب منزلك',
    url: 'https://www.youtube.com/',
    icon: 'delivery',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_package',
    title: 'الباقات والعروض التوفيرية الشاملة',
    subtitle: 'وفّر أكثر مع باقاتنا المتكاملة المصممة لك',
    url: 'https://www.youtube.com/',
    icon: 'package',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_video',
    title: 'قناتنا الرسمية على منصة يوتيوب',
    subtitle: 'فيديوهات وشروحات وتجارب بصرية أسبوعية',
    url: 'https://www.youtube.com/',
    icon: 'video',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_music',
    title: 'مكتبة المقاطع الصوتية والموسيقى',
    subtitle: 'استمع لأحدث المقطوعات الصوتية والألحان',
    url: 'https://www.youtube.com/',
    icon: 'music',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_podcast',
    title: 'استمع لحلقات البودكاست الصوتية',
    subtitle: 'حوارات ملهمة وقصص نجاح تثري فكرك وتجاربك',
    url: 'https://www.youtube.com/',
    icon: 'podcast',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_headphones',
    title: 'الكتب الصوتية والمحتوى المسموع',
    subtitle: 'استمع لأفضل ملخصات الكتب في أي وقت وأينما كنت',
    url: 'https://www.youtube.com/',
    icon: 'headphones',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_camera',
    title: 'معرض الأعمال وجلسات التصوير الفوتوغرافي',
    subtitle: 'شاهد أحدث أعمال التصوير الاحترافي وتجاربنا',
    url: 'https://www.youtube.com/',
    icon: 'camera',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_book',
    title: 'قراءة وتحميل الكتاب الإلكتروني المجاني',
    subtitle: 'دليل عملي شامل لتطوير مهاراتك من الصفر',
    url: 'https://www.youtube.com/',
    icon: 'book',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_article',
    title: 'المقالات والأبحاث المتخصصة PDF',
    subtitle: 'أوراق بحثية ودراسات سوقية معمقة للتحميل',
    url: 'https://www.youtube.com/',
    icon: 'article',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_download',
    title: 'تحميل المرفقات والنماذج الجاهزة',
    subtitle: 'ملفات عمل وقوالب قابلة للتعديل والاستخدام المباشر',
    url: 'https://www.youtube.com/',
    icon: 'download',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_code',
    title: 'مستودع الأكواد والمشاريع البرمجية',
    subtitle: 'مشاريع مفتوحة المصدر ومكتبات برمجية متطورة',
    url: 'https://www.youtube.com/',
    icon: 'code',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_education',
    title: 'التسجيل في الدورة التدريبية الشاملة',
    subtitle: 'تعلّم خطوة بخطوة حتى الاحتراف الكامل مع شهادة معتمدة',
    url: 'https://www.youtube.com/',
    icon: 'education',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_sparkles',
    title: 'العضوية الذهبية والوصول الحصري VIP',
    subtitle: 'مزايا حصرية ومحتوى خاص متاح للأعضاء فقط',
    url: 'https://www.youtube.com/',
    icon: 'sparkles',
    highlight: true,
    is_active: true,
  },
  {
    id: 'sample_flame',
    title: 'المنتجات الأكثر طلباً وشهرة Trending',
    subtitle: 'العناصر الأكثر مبيعاً وتقييماً من الزوار والعملاء',
    url: 'https://www.youtube.com/',
    icon: 'flame',
    highlight: true,
    is_active: true,
  },
  {
    id: 'sample_star',
    title: 'تقييمات وآراء العملاء وتجاربهم',
    subtitle: 'شاهد تقييمات 5 نجوم وتجارب عملائنا الحقيقية',
    url: 'https://www.youtube.com/',
    icon: 'star',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_heart',
    title: 'مبادراتنا الاجتماعية ودعم المجتمع',
    subtitle: 'ساهم معنا في دعم المشاريع الإنسانية والخيرية',
    url: 'https://www.youtube.com/',
    icon: 'heart',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_rocket',
    title: 'إطلاق المشروع الجديد والموقع التجريبي',
    subtitle: 'كن أول من يجرّب ميزاتنا الجديدة قبل الجميع',
    url: 'https://www.youtube.com/',
    icon: 'rocket',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_award',
    title: 'الجوائز والشهادات والاعتمادات الرسمية',
    subtitle: 'سجل حافل بالتميز والإنجازات المعتمدة محلياً ودولياً',
    url: 'https://www.youtube.com/',
    icon: 'award',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_verified',
    title: 'الحسابات والقنوات الرسمية الموثقة',
    subtitle: 'تأكد من متابعتنا عبر القنوات المعتمدة الرسمية فقط',
    url: 'https://www.youtube.com/',
    icon: 'verified',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_idea',
    title: 'الأفكار الإبداعية وبنك الإلهام',
    subtitle: 'أفكار ملهمة وحلول مبتكرة لتطوير مشاريعك',
    url: 'https://www.youtube.com/',
    icon: 'idea',
    highlight: false,
    is_active: true,
  },
  {
    id: 'sample_zap',
    title: 'الخدمات الفورية والحلول السريعة',
    subtitle: 'تنفيذ فوري ودعم عاجل لجميع احتياجاتك',
    url: 'https://www.youtube.com/',
    icon: 'zap',
    highlight: false,
    is_active: true,
  },
]

export function getPresetSampleData(iconId: string): { title: string; subtitle: string; url: string } {
  const sample = DEFAULT_SAMPLE_LINKS.find((s) => s.icon === iconId)
  if (sample) {
    return { title: sample.title, subtitle: sample.subtitle || '', url: sample.url }
  }
  return {
    title: 'رابط مباشر',
    subtitle: 'تصفح وأطلب بكل سهولة',
    url: 'https://www.youtube.com/',
  }
}

