-- ============================================================
-- 037_whatsapp_evolution_api.sql
--
-- Adds Evolution API as a second optional WhatsApp connection
-- method alongside the existing Meta Business API.
--
-- Design decisions
-- ─────────────────
-- * We extend the existing whatsapp_config table rather than
--   creating a second one. The UNIQUE(account_id) constraint
--   already enforces one active WhatsApp connection per account,
--   which is the correct invariant for both methods.
--
-- * A new `connection_type` column ('meta' | 'evolution') makes
--   the active method explicit. All pre-existing rows are
--   backfilled to 'meta' (their original intent).
--
-- * Evolution-specific columns are nullable; they are NULL for
--   every 'meta' row. Meta-specific columns (phone_number_id,
--   access_token, etc.) remain nullable for 'evolution' rows.
--   This avoids a NOT NULL migration that would break
--   existing data.
--
-- * The evolution_api_key column stores the per-instance key
--   encrypted with the same AES-256-GCM scheme used for Meta
--   access_token / verify_token (see lib/whatsapp/encryption.ts
--   and ENCRYPTION_KEY env var). Never stored in plaintext.
--
-- What this migration does NOT touch
-- ────────────────────────────────────
-- * No existing column is modified or dropped.
-- * No existing constraint is dropped or replaced.
-- * No existing RLS policy is changed.
-- * No existing index is changed.
-- * All previous migrations (001-036) remain untouched.
--
-- Idempotent -- safe to run multiple times.
-- ============================================================

-- ============================================================
-- 1. Add connection_type discriminator
--    DEFAULT 'meta' backfills all existing rows automatically.
-- ============================================================
ALTER TABLE whatsapp_config
  ADD COLUMN IF NOT EXISTS connection_type TEXT
    NOT NULL DEFAULT 'meta'
    CHECK (connection_type IN ('meta', 'evolution'));

-- ============================================================
-- 2. Add Evolution-specific columns (all nullable)
--
--   evolution_server_url
--     Full base URL of the SaaS-owned Evolution API server.
--     Example: https://evolution.example.com
--     Set by the server-side route from the EVOLUTION_SERVER_URL
--     env var -- the user never types this.
--
--   evolution_api_key
--     Per-instance API key generated by Evolution when the
--     instance is created. Stored AES-256-GCM encrypted with
--     the same ENCRYPTION_KEY used for Meta tokens.
--
--   evolution_instance_name
--     Stable identifier for the instance on the Evolution
--     server. Unique within that server. Derived from
--     account_id at creation time so it is deterministic and
--     idempotent on retry.
--
--   evolution_connected_phone
--     The WhatsApp number that connected via QR scan, in
--     E.164 format. Populated by the Evolution webhook event
--     after successful scan. Displayed in the UI as proof of
--     connection.
-- ============================================================
ALTER TABLE whatsapp_config
  ADD COLUMN IF NOT EXISTS evolution_server_url      TEXT,
  ADD COLUMN IF NOT EXISTS evolution_api_key         TEXT,
  ADD COLUMN IF NOT EXISTS evolution_instance_name   TEXT,
  ADD COLUMN IF NOT EXISTS evolution_connected_phone TEXT;

-- ============================================================
-- 3. Index on connection_type
--    Cheap to maintain; useful for the admin dashboard query
--    "how many accounts use each method?" and for any future
--    fan-out that targets only evolution rows.
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_whatsapp_config_connection_type
  ON whatsapp_config (connection_type);

-- ============================================================
-- 4. Verify backfill is correct
--    Every row that existed before this migration should now
--    have connection_type = 'meta'. This DO block raises a
--    WARNING (not an error) if any row somehow ended up with
--    a NULL -- which cannot happen given the NOT NULL DEFAULT,
--    but is here as a belt-and-braces sanity check.
-- ============================================================
DO $$
DECLARE
  null_count INT;
BEGIN
  SELECT COUNT(*) INTO null_count
  FROM whatsapp_config
  WHERE connection_type IS NULL;

  IF null_count > 0 THEN
    RAISE WARNING
      '037_whatsapp_evolution_api: % row(s) in whatsapp_config have NULL connection_type -- this should not happen with DEFAULT ''meta''. Inspect and repair.',
      null_count;
  ELSE
    RAISE NOTICE
      '037_whatsapp_evolution_api: backfill OK -- all rows have connection_type set.';
  END IF;
END $$;
